services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=SwiftRoute
      - DATABASE_PORT=5432
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=SwiftRoute
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./Database/DB.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge